--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	F:/DJS130/DJS130_final/al_ip/CRAM.vhd
 -- Date	:	2024 11 12
 -- TD version	:	5.6.119222
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY CRAM IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	ocea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	rsta	: IN STD_LOGIC
	);
END CRAM;

ARCHITECTURE struct OF CRAM IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			ADDR_WIDTH_A	=> 12,
			DATA_DEPTH_A	=> 4096,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_B	=> 12,
			DATA_DEPTH_B	=> 4096,
			MODE			=> "SP",
			REGMODE_A	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea	=> cea,
			ceb	=> '0',
			clka	=> clka,
			clkb	=> '0',
			wea	=> wea,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			web	=> '0',
			rsta	=> rsta,
			rstb	=> '0',
			doa	=> doa,
			dob	=> OPEN,
			ocea	=> ocea,
			oceb	=> '0'
		);

END struct;
